# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IRCMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irc_channel', models.CharField(max_length=49)),
                ('date', models.DateTimeField(db_index=True)),
                ('nick', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ircmessage',
            unique_together=set([('nick', 'message', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='ircmessage',
            index_together=set([('irc_channel', 'date')]),
        ),
    ]
